/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.amex.paymentstub.services;

import javax.validation.Valid;

import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;

import com.amex.paymentstub.model.ApiResponseMessage;
import com.amex.paymentstub.model.AuthPushFields;

public interface PaymentIdApiService {
	
	// declaring fields required for validation

    ApiResponseMessage createAuthorization(@RequestHeader(value="App-Name", required=true) String appName,@PathVariable("paymentId") Long paymentId,  @Valid @RequestBody AuthPushFields body);

}
